---
###############################################################################
# Â© Copyright IBM Corporation 2020, 2021
###############################################################################

# tasks file for print_hc_buffer
###########################################################################
# skeleton for HZSPRNT
###########################################################################
- name: 'send jcl template'
  block:
    - set_fact:
        eager_role_path: '{{ role_path }}'

    - include_role:
        name: send-template
      vars:
        path: '{{ eager_role_path }}/templates/HZSPRINT.J2'

    - name: Get expiring certs report for {{ hc_check }}
      ibm.ibm_zos_core.zos_job_submit:
        # src: USER.PRIVATE.PROCLIB(HZSPRINT)
        # location: DATA_SET
        # wait: true
        src: '{{ uss_file_path }}/HZSPRINT.J2'
        location: USS
        wait: true
      register: hc_job_output

# - name: "{{task_description}}"
#   ibm.ibm_zos_core.zos_mvs_raw:
#     pgm: HZSPRNT
#     auth: yes
#     parm: "REGION=0M,PARM={{parm_string}}"
#     dds:
#       - dd_output:
#           dd_name: SYSOUT
#           return_content:
#             type: text
