---
# tasks file for zcee_create_format_zfs
- name: Create an LDS
  ibm.ibm_zos_core.zos_data_set:
    name: "{{ zcon_file_system_hlq }}.{{softwareServiceInstanceName}}"
    type: lds
    sms_data_class: "{{ zcon_zfs_dataclass }}"
  when: 
    - zcon_zfs_dataclass is defined 
    - zcon_zfs_dataclass != '' 
 
- name: Create an LDS
  ibm.ibm_zos_core.zos_data_set:
    name: "{{ zcon_file_system_hlq }}.{{softwareServiceInstanceName}}"
    type: lds
    volume: "{{ zcon_zos_vsam_volume }}"
  when: not DFS_SMS_ENVIRONMENT 

- name: Format LDS as ZFS
  command: zfsadm format -aggregate "{{ zcon_file_system_hlq }}.{{softwareServiceInstanceName}}"
  register: response
  failed_when: response.rc > 0 and "Aggregate contains file system" not in response.stderr and "Aggregate is attached" not in response.stderr         
