galaxy_info:
  author: An Lam
  description: Ansible Solution Automation developer
  company: IBM

  license: "Apache License, Version 2.0"

  min_ansible_version: 2.9
  galaxy_tags:
    - z
    - zos
    - z_os
    - ibm_zos_ims
