---
# tasks file for install_zconbt

- name: Check if zconbt available for install
  ansible.builtin.stat:
    path: "{{ role_path }}/files/{{ zconbt_compressed_name }}"
  register: zconbt_local_available
  delegate_to: localhost

- name: Check if zconbt.zip available on target host
  ansible.builtin.stat:
    path: "{{ ZOS_CONNECT_HOME }}/zconbt.zip"
  register: zconbt_zip_available

- name: Check if zconbt already on target
  ansible.builtin.stat:
    path: "{{ install_path }}/bin/zconbt"
  register: zconbt_installed

- name: Copy and extract zconbt
  when: zconbt_local_available.stat.exists and not zconbt_installed.stat.exists
  block:
    - name: Copy zconbt
      ansible.builtin.copy:
        src: "{{ role_path }}/files/{{ zconbt_compressed_name }}"
        dest: "{{ install_path }}/{{ zconbt_compressed_name}}" # extracts to bin folder

    - name: Extract extract on target
      ansible.builtin.shell: "{{ utility_path }}/bzip2 -df {{ zconbt_compressed_name }}; tar -Co . -xf zconbt.tar; rm zconbt.tar" # ; mv ./bin/zconbt* . ; rmdir ./bin 2>/dev/null'
      args:
        chdir: "{{ install_path }}"

- name: Unzip existing zconbt.zip if available
  when: zconbt_zip_available.stat.exists and not zconbt_local_available.stat.exists and not zconbt_installed.stat.exists
  block:
    - name: Unzip zconbt.zip into the install_path
      ansible.builtin.shell: "unzip {{ ZOS_CONNECT_HOME }}/zconbt.zip -d {{ install_path }}"
      args:
        chdir: "{{ install_path }}"
