# =================================================================
# Copyright 2021 https://github.com/openshift/installer
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# =================================================================

# =================================================================
# Licensed Materials - Property of IBM
#
# (c) Copyright IBM Corp. 2021 All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# =================================================================
#
# Change Summary: 
# - Move port creation to network.yaml
# - Delete unnecessary Ansible tasks
# - Use random strings to name compute nodes

# Required Python packages:
#
# ansible
# openstackclient
# openstacksdk
# netaddr

- name: 'Import common yaml'
  import_tasks: common.yaml

- name: Export infra ID
  shell:
    cmd: "jq -r .infraID metadata.json"
  register: infra_id

- name: 'Create the compute servers'
  os_server:
    name: "{{ item.1 }}-{{ item.0 }}"
    image: "rhcos"
    flavor: "{{ os_flavor_worker }}"
    auto_ip: no
    availability_zone: "{{ create_server_zone }}"
    timeout: "{{ create_server_timeout|int * 60 }}" 
    userdata: "{{ lookup('file', [item.1, item.0, 'ignition.json'] | join('-')) | string }}"
    nics:
    - port-name: "{{ os_port_worker }}-{{ item.0 }}"
    meta: "{{ cluster_id_tag }}"
  with_indexed_items: "{{ [os_compute_server_name] * os_compute_nodes_number }}"
  when:
  - disk_type == "dasd"

- name: 'Convert compute node flavor from value into number'
  command:
    cmd: "openstack flavor show {{ os_flavor_worker }} -c disk -f value"
  register: compute_flavor_size
  when:
  - disk_type == "scsi"

- name: 'Create the compute servers with default boot volume'
  os_server:
    name: "{{ item.1 }}-{{ item.0 }}"
    image: "rhcos"
    flavor: "{{ os_flavor_worker }}"
    auto_ip: no
    availability_zone: "{{ create_server_zone }}"
    timeout: "{{ create_server_timeout|int * 60 }}" 
    userdata: "{{ lookup('file', [item.1, item.0, 'ignition.json'] | join('-')) | string }}"
    nics:
    - port-name: "{{ os_port_worker }}-{{ item.0 }}"
    meta: "{{ cluster_id_tag }}"
    boot_from_volume: True
    volume_size: "{{ compute_flavor_size.stdout_lines[0]}}"
    terminate_volume: True
  with_indexed_items: "{{ [os_compute_server_name] * os_compute_nodes_number }}"
  when:
  - disk_type == "scsi"
  - volume_type_id is not defined

- name: 'Create compute boot volume'
  os_volume:
    state: present
    name: "{{ item.1 }}-{{ item.0 }}-boot"
    image: "rhcos"
    size: "{{ compute_flavor_size.stdout_lines[0]}}"
    volume_type: "{{ volume_type_id }}"
    metadata: "{{ cluster_id_tag }}"
    timeout: "{{ create_server_timeout|int * 60 }}" 
  with_indexed_items: "{{ [os_compute_server_name] * os_compute_nodes_number }}"
  when:
  - disk_type == "scsi"
  - volume_type_id is defined

- name: 'Set compute volume bootable'
  shell: openstack volume set --bootable "{{ item.1 }}-{{ item.0 }}-boot"
  with_indexed_items: "{{ [os_compute_server_name] * os_compute_nodes_number }}"
  when: 
  - disk_type == "scsi"
  - volume_type_id is defined

- name: 'Create the compute server with boot volume'
  os_server:
    name: "{{ item.1 }}-{{ item.0 }}"
    flavor: "{{ os_flavor_worker }}"
    boot_volume: "{{ item.1 }}-{{ item.0 }}-boot"
    auto_ip: no
    availability_zone: "{{ create_server_zone }}"
    timeout: "{{ create_server_timeout|int * 60 }}" 
    userdata: "{{ lookup('file', [item.1, item.0, 'ignition.json'] | join('-')) | string }}"
    nics:
    - port-name: "{{ os_port_worker }}-{{ item.0 }}"
    meta: "{{ cluster_id_tag }}"
    terminate_volume: True
  with_indexed_items: "{{ [os_compute_server_name] * os_compute_nodes_number }}"
  when:
  - disk_type == "scsi"
  - volume_type_id is defined