---
# Tasks for Common Queue Services (CQS)
- name: CQS
  collections:
    - ibm.ibm_zos_core
    - ibm.ibm_zos_ims

  block:

    - ansible.builtin.set_fact:
        ip_config: '{{ role_path }}/templates/ip_config.txt'
        sl_config: '{{ role_path }}/templates/sl_config.txt'
        sg_config: '{{ role_path }}/templates/sg_config.txt'
        sq_config: '{{ role_path }}/templates/sq_config.txt'

    # AL: Replace JCL with zos_mvs_raw
    - name: Copy input to member CQSIP000
      ibm.ibm_zos_core.zos_mvs_raw:
        pgm: IEBGENER
        auth: false
        dds:
          - dd_data_set:
              dd_name: sysut2
              data_set_name: "{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.PROCLIB(CQSIP000)"
              disposition: shr
          - dd_dummy:
              dd_name: sysin
          - dd_input:
              dd_name: sysut1
              content: "{{ lookup('template', '{{ ip_config }}') }}"
          - dd_output:
              dd_name: sysprint
              return_content:
                type: text
      when: cqs == "config"

    - name: Copy input to member CQSSL000
      ibm.ibm_zos_core.zos_mvs_raw:
        pgm: IEBGENER
        auth: false
        dds:
          - dd_data_set:
              dd_name: sysut2
              data_set_name: "{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.PROCLIB(CQSSL000)"
              disposition: shr
          - dd_dummy:
              dd_name: sysin
          - dd_input:
              dd_name: sysut1
              content: "{{ lookup('template', '{{ sl_config }}') }}"
          - dd_output:
              dd_name: sysprint
              return_content:
                type: text
      when: cqs == "config"

    - name: Copy input to member CQSSG000
      ibm.ibm_zos_core.zos_mvs_raw:
        pgm: IEBGENER
        auth: false
        dds:
          - dd_data_set:
              dd_name: sysut2
              data_set_name: "{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.PROCLIB(CQSSG000)"
              disposition: shr
          - dd_dummy:
              dd_name: sysin
          - dd_input:
              dd_name: sysut1
              content: "{{ lookup('template', '{{ sg_config }}') }}"
          - dd_output:
              dd_name: sysprint
              return_content:
                type: text
      when: cqs == "config"

    - name: Copy input to member DFSSQ000
      ibm.ibm_zos_core.zos_mvs_raw:
        pgm: IEBGENER
        auth: false
        dds:
          - dd_data_set:
              dd_name: sysut2
              data_set_name: "{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.PROCLIB(DFSSQ000)"
              disposition: shr
          - dd_dummy:
              dd_name: sysin
          - dd_input:
              dd_name: sysut1
              content: "{{ lookup('template', '{{ sq_config }}') }}"
          - dd_output:
              dd_name: sysprint
              return_content:
                type: text
      when: cqs == "config"

    # Query CQS status
    - name: Query CQS status
      ibm.ibm_zos_ims.ims_command:
        command: QUERY IMSPLEX NAME(*) TYPE(CQS) SHOW(STATUS)
        plex: '{{ DFS_IMSPlex }}'
      when: cqs == "query"
