---
# MPP Services
- name: MPP Services
  collections:
    - ibm.ibm_zos_core
    - ibm.ibm_zos_ims

  block:

      - name: Stop MMP Regions
        ims_command:
          command: 'STOP REGION JOBNAME {{ DFS_IMS_SSID }}MPP{{ item }}'
          plex: '{{ DFS_IMSPlex }}'
        with_sequence: start={{ REGION_NUM }} end={{ REGION_NUM }}
        ignore_errors: true
