# =================================================================
# Licensed Materials - Property of IBM
#
# (c) Copyright IBM Corp. 2022 All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# =================================================================

---
- name: 'Import common yaml'
  ansible.builtin.include_tasks: "{{ playbook_dir }}/common.yaml"

- name: Verify openshift minor version
  ansible.builtin.shell: |
    version=$(wget -q -O - https://mirror.openshift.com/pub/openshift-v4/{{ ansible_architecture }}/dependencies/rhcos/{{ openshift_version }}/{{ openshift_version }}.{{ openshift_minor_version }}/sha256sum.txt | grep rhcos | wc -l)
    if [ $version -eq "0" ] || [ "{{ openshift_minor_version }}" -eq "latest" ]; then
      echo $(wget -q -O - https://mirror.openshift.com/pub/openshift-v4/{{ ansible_architecture }}/dependencies/rhcos/{{ openshift_version }}/latest/sha256sum.txt | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+" | head -n1)
    else
      echo "{{ openshift_version }}.{{ openshift_minor_version }}"
    fi
  register: icic_ocp_version

- name: 'Set fact for openshift rhcos url'
  ansible.builtin.set_fact:
    openshift_rhcos_url: "https://mirror.openshift.com/pub/openshift-v4/{{ ansible_architecture }}/dependencies/rhcos/{{ openshift_version }}/{{ icic_ocp_version.stdout }}"
    openshift_install_dir: "."

- name: Download checksum for the rhcos image
  ansible.builtin.get_url:
    url: "{{ openshift_rhcos_url }}/sha256sum.txt"
    dest: "{{ openshift_install_dir }}/.sha256sum_remote.txt"
    force: true

- name: Get checksum for the rhcos image
  ansible.builtin.slurp:
    src: "{{ openshift_install_dir }}/.sha256sum_remote.txt"
  register: openshift_rhcos_checksum_results

- name: Get existing RHCOS image from ICIC glance
  ansible.builtin.shell: |
    if [ {{ vm_type }} == "kvm" ]; then
      a=$(openstack image list --format value| grep -w 'icic_rhcos_{{ vm_type }}_{{ disk_type }}_{{ openshift_version }}_{{ openshift_minor_version }}'| awk '{print$1}')
    else
      a=$(openstack image list --format value| grep -w 'icic_rhcos_{{ vm_type }}_{{ disk_type }}_{{ openshift_version }}_{{ openshift_minor_version }}'| awk '{print$1}')
    fi
    if [ -z $a ]; then echo empty; else echo $a; fi
  register: icic_rhcos_id

- name: Get existing RHCOS image SHA256 from ICIC glance
  ansible.builtin.shell: |
    if [ ! -z "{{ icic_rhcos_id.stdout }}" ]; then
      echo $(openstack image show --format json -c properties {{ icic_rhcos_id.stdout }} | grep gz_sha256 | cut -d ':' -f2 | sed 's/[^a-zA-Z0-9]//g')
    else
      echo "rhcos"
    fi
  register: icic_rhcos_sha256_value
  when: icic_rhcos_id.stdout != "empty"

- name: Compare existing rhcos image with sha256
  ansible.builtin.shell: |
    if [ ! -z "{{ icic_rhcos_id.stdout }}" ] && [ {{ vm_type }} = "zvm" ] && [ {{ disk_type }} = "scsi" ] ; then
      count=$(grep -E '{{ icic_rhcos_sha256_value.stdout }}.*rhcos-metal.s390x.raw.gz' .sha256sum_remote.txt | wc -l)
    elif [ ! -z "{{ icic_rhcos_id.stdout }}" ] && [ {{ vm_type }} = "zvm" ] && [ {{ disk_type }} = "dasd" ]; then
      count=$(grep -E '{{ icic_rhcos_sha256_value.stdout }}.*rhcos-dasd.s390x.raw.gz' .sha256sum_remote.txt | wc -l)
    elif [ ! -z "{{ icic_rhcos_id.stdout }}" ] && [ {{ vm_type }} = "kvm" ]; then
      count=$(grep -E '{{ icic_rhcos_sha256_value.stdout }}.*rhcos-openstack.*' .sha256sum_remote.txt | wc -l)
    else
      count=0
    fi
    echo $count
  register: use_local_rhcos
  when: icic_rhcos_id.stdout != "empty"

# - name: Remove the existing RHCOS image without sha256 from ICIC glance
#   ansible.builtin.shell: "openstack image delete {{ item }}"
#   with_items: "{{ icic_rhcos_id.stdout_lines }}"
#   when:
#   - icic_rhcos_id.stdout != ""
#   - icic_rhcos_sha256_value.stdout == ""

# Don't remove the existing RHCOS image with unmatch sha256 for Day2 operation
#- name: Remove the existing RHCOS image with unmatch sha256 from ICIC glance
#  ansible.builtin.shell: "openstack image delete {{ item }}"
#  with_items: "{{ icic_rhcos_id.stdout_lines }}"
#  when:
#    - icic_rhcos_id.stdout != "empty"
#    - use_local_rhcos.stdout | int != 1

- name: Get new RHCOS image from ICIC glance
  ansible.builtin.shell: |
    out=$(openstack image list | grep -w 'icic_rhcos_{{ vm_type }}_{{ disk_type }}_{{ openshift_version }}_{{ openshift_minor_version }}' | wc -l)
    echo $out
  register: icic_rhcos_count

- name: Download openshift rhcos metal image
  ansible.builtin.get_url:
    url: "{{ openshift_rhcos_url }}/rhcos-{{ icic_ocp_version.stdout }}-s390x-metal.s390x.raw.gz"
    dest: "{{ openshift_install_dir }}/rhcos-{{ icic_ocp_version.stdout }}-s390x.gz"
  when:
    - vm_type == "zvm"
    - disk_type == "scsi"
    - icic_rhcos_count.stdout | int != 1

- name: Download openshift rhcos dasd image
  ansible.builtin.get_url:
    url: "{{ openshift_rhcos_url }}/rhcos-{{ icic_ocp_version.stdout }}-s390x-dasd.s390x.raw.gz"
    dest: "{{ openshift_install_dir }}/rhcos-{{ icic_ocp_version.stdout }}-s390x.gz"
  when:
    - vm_type == "zvm"
    - disk_type == "dasd"
    - icic_rhcos_count.stdout | int != 1

- name: Download openshift rhcos qcow2 image
  ansible.builtin.get_url:
    url: "{{ openshift_rhcos_url }}/rhcos-{{ icic_ocp_version.stdout }}-s390x-openstack.s390x.qcow2.gz"
    dest: "{{ openshift_install_dir }}/rhcos-{{ icic_ocp_version.stdout }}-s390x.gz"
  when:
    - vm_type == "kvm"
    - icic_rhcos_count.stdout | int != 1

- name: Generate sha256 for local rhcos-{{ icic_ocp_version.stdout }}-s390x.gz
  ansible.builtin.shell: "sha256sum {{ openshift_install_dir }}/rhcos-{{ icic_ocp_version.stdout }}-s390x.gz > .sha256sum_local.txt"
  when:
    - icic_rhcos_count.stdout | int != 1

- name: Get sha256 for local rhcos-{{ icic_ocp_version.stdout}}-s390x.gz
  ansible.builtin.shell: "cat .sha256sum_local.txt | awk -F ' ' '{print $1}'"
  register: openshift_rhcos_sha256_results
  when:
    - icic_rhcos_count.stdout | int != 1

- name: Unzip openshift rhcos image
  ansible.builtin.command:
    cmd: |
        gzip -d -f rhcos-{{ icic_ocp_version.stdout }}-s390x.gz
  when: icic_rhcos_count.stdout | int != 1

- name: Upload RHCOS image to ICIC glance
  ansible.builtin.command:
    cmd: openstack image create --disk-format=raw  --property gz_sha256={{ openshift_rhcos_sha256_results.stdout}} --property architecture=s390x --property os_name=Linux --property os_version=RHCOS{{ openshift_version }} --property os_distro=RHCOS{{ openshift_version }} --property hypervisor_type=ZVM --property disk_type=SCSI --file=rhcos-{{ icic_ocp_version.stdout }}-s390x icic_rhcos_{{ vm_type }}_{{ disk_type }}_{{ openshift_version }}_{{ openshift_minor_version }}
  when:
    - vm_type == "zvm"
    - disk_type == "scsi"
    - icic_rhcos_count.stdout | int != 1

- name: Upload RHCOS image to ICIC glance
  ansible.builtin.command:
    cmd: openstack image create --disk-format=raw  --property gz_sha256={{ openshift_rhcos_sha256_results.stdout }} --property architecture=s390x --property os_name=Linux --property os_version=RHCOS{{ openshift_version }} --property os_distro=RHCOS{{ openshift_version }} --property hypervisor_type=ZVM --property disk_type=DASD --file=rhcos-{{ icic_ocp_version.stdout }}-s390x icic_rhcos_{{ vm_type }}_{{ disk_type }}_{{ openshift_version }}_{{ openshift_minor_version }}
  when:
    - vm_type == "zvm"
    - disk_type == "dasd"
    - icic_rhcos_count.stdout | int != 1

- name: Upload RHCOS image to ICIC glance
  ansible.builtin.command:
    cmd: openstack image create --disk-format=qcow2 --property gz_sha256={{ openshift_rhcos_sha256_results.stdout }} --property architecture=s390x --property os_name=Linux --property os_version=RHCOS{{ openshift_version }} --property os_distro=RHCOS{{ openshift_version }} --property hypervisor_type=kvm --file=rhcos-{{ icic_ocp_version.stdout }}-s390x icic_rhcos_{{ vm_type }}_{{ disk_type }}_{{ openshift_version }}_{{ openshift_minor_version }}
  when:
    - vm_type == "kvm"
    - disk_type == "dasd"
    - icic_rhcos_count.stdout | int != 1
    - volume_type_id is not defined


- name: Upload RHCOS image to ICIC glance
  ansible.builtin.command:
    cmd: openstack image create --disk-format=qcow2 --property disk_type=SCSI --property gz_sha256={{ openshift_rhcos_sha256_results.stdout }} --property architecture=s390x --property os_name=Linux --property disk_type=SCSI --property os_version=RHCOS{{ openshift_version }} --property os_distro=RHCOS{{ openshift_version }} --property hypervisor_type=kvm --file=rhcos-{{ icic_ocp_version.stdout }}-s390x icic_rhcos_{{ vm_type }}_{{ disk_type }}_{{ openshift_version }}_{{ openshift_minor_version }}
  when:
    - vm_type == "kvm"
    - icic_rhcos_count.stdout | int != 1
    - disk_type == "scsi"

- name: Remove local RHCOS image
  ansible.builtin.file:
    state: absent
    path: rhcos-{{ icic_ocp_version.stdout }}-s390x
  when: icic_rhcos_count.stdout | int != 1
