###############################################################################
# Â© Copyright IBM Corporation 2021
#
# Changelog
#  All notable changes to this sample will be documented in this playbook
#
# [1.0.0] - 2021-04-21
#  - Released initial version
###############################################################################

# directory path that the provisioning role uses to capture various information (in JSON format) about the provisioned instance.
# "/tmp" is used as place holder and should be changed if "/tmp" content is removed frequently.
instance_record_dir: "/tmp" 

# total retry attempts allowed before the task exits with failure, waiting on the instance action to complete
api_polling_retry_count: 50

# interval time (in seconds) for each polling request
api_polling_interval_seconds: 10

# user name to be used for authenticating with the z/OSMF server
# zmf_user: zosmf_user_name

# password to be used for authenticating with the z/OSMF server
# zmf_password: zosmf_password