# Copyright (c) IBM Corporation 2024

galaxy_info:
  author: Andy Nguyen
  description: Ansible z/OS Core Developer
  company: IBM
  license: "Apache License, Version 2.0"
  min_ansible_version: "2.9"
  galaxy_tags:
    - z
    - zos
    - z_os
    - ibm_zos_core
