---
# defaults file for provision-ims-dbdc

# the path where JCL and other scripts will be stored
uss_file_path: /tmp
# the path where additional utilities are located
uss_utilities_path: /tmp

ARC: '03'

# Default vars for proclib services
send: false
delete: false
create_sample: false
add: false
bpeconfg: false
copy: false
copy_to_jobs: false
copy_stage_libs: false
