---
# Copyright (c) IBM Corporation 2021

# tasks file for order_ptf

# Order PTF from IBM
- name: "ORDER PTF {{ptfs}} from IBM server"
  ibm.ibm_zos_core.zos_mvs_raw:
    pgm: GIMSMP
    auth: "yes"
    dds:
      - dd_data_set:
          dd_name: "SMPCSI"
          data_set_name: "{{ global_csi }}"
          disposition: old
      - dd_output:
          dd_name: "SMPOUT"
          return_content:
              type: text
      - dd_unix:
          dd_name: "SMPNTS"
          path: "{{smpe_root}}/smpnts/"
      - dd_input:
          dd_name: "SMPCNTL"
          content:
            - 'SET  BOUNDARY(GLOBAL) .'
            - 'RECEIVE ORDER('
            - '           CONTENT(PTFS({{ ptfs }}))'
            - '           ORDERSERVER(SERVINFO)'
            - '           CLIENT(CLNTINFO)'
            - '              )'
            - DELETEPKG.
      - dd_input:
          dd_name: "SERVINFO"
          content: "{{ server_info }}"
      - dd_input:
          dd_name: "CLNTINFO"
          content: "{{ client_info }}"
  register: order_result

- name: "LIST HOLDDATA"
  ibm.ibm_zos_core.zos_mvs_raw:
    pgm: GIMSMP
    auth: "yes"
    dds:
      - dd_data_set:
          dd_name: "SMPCSI"
          data_set_name: "{{ global_csi }}"
          disposition: old

      - dd_output:
          dd_name: "SMPOUT"
          return_content:
              type: text
      - dd_output:
          dd_name: "SMPLIST"
          return_content:
              type: text
      - dd_input:
          dd_name: "SMPCNTL"
          content:
            - 'SET  BOUNDARY(GLOBAL) .'
            - 'LIST SYSMOD({{ ptfs }}) HOLDDATA .'
  when: order_result.ret_code.code <= 4