---
# defaults file for ims_cobol_check_acblib
ROUTE: '{{ DFS_IMS_SSID }}'

# This will be changed dynamically during application deployment
# INACTIVE_ACBLIB: '{{ IMSBANK_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.ACBLIBA'
