---
###############################################################################
# Â© Copyright IBM Corporation 2020, 2021
###############################################################################

# tasks file for issue_operator_cmd

##########################################################################
# Issue zos command
##########################################################################
- name: "{{ task_description }}"
  ibm.ibm_zos_core.zos_tso_command:
    commands: "{{command}}"



