---
################################################################################
# Â© Copyright IBM Corporation 2020
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)
################################################################################

- name: Git pull a repository
  git:
    repo: "{{ git_addr }}"
    dest: "{{ checkout_dir }}"
  register: result

