---
# IEF Services
- name: IEF Services
  collections:
    - ibm.ibm_zos_core
    - ibm.ibm_zos_ims

  block:

    - block:
        - ansible.builtin.set_fact:
            eager_role_path: '{{role_path}}'

        - ansible.builtin.include_role:
            name: send-templates
          vars:
            template_path: '{{ eager_role_path }}/templates/IEFJOBSX.j2'

        - ansible.builtin.include_role:
            name: submit-rexx
            public: true
          vars:
            rexx_name: 'IEFJOBSX.j2'
            max_rc: 0

      when: iefjobs == "delete"

    - block:
        - ansible.builtin.set_fact:
            eager_role_path: '{{role_path}}'


        - ansible.builtin.include_role:
            name: send-templates
          vars:
            template_path: '{{ eager_role_path }}/templates/IEFJOBS.j2'

      when: iefjobs == "create" and not provision

    - ansible.builtin.include_role:
        name: submit-rexx
        public: true
      vars:
        rexx_name: 'IEFJOBS.j2'
        max_rc: 0

      when: iefjobs == "create"
