---
###############################################################################
# Â© Copyright IBM Corporation 2024
###############################################################################

# tasks file for issue_operator_cmd

##########################################################################
# Issue zos command
##########################################################################
- name: "{{ task_description }}"
  ibm.ibm_zos_core.zos_operator:
    cmd: "{{command}}"
  register: zos_operator_output
