###############################################################################
# Copyright (c) IBM Corporation 2020
###############################################################################

###############################################################################
# This sample playbook demonstrates how to submit jobs, query and retrieve job 
# output using modules included in the Red Hat Ansible Certified  Content for 
# IBM Z core collection.
#
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventory job-submission.yaml
#
# Notes:
#  This sample demonstrates ways to submit, query and retrieve job output using 
#  Ansible z/OS core modules. Each module has options available on how 
#  automation can be controlled. This sample does not demonstrate all options, 
#  refer to documentation or ansible-doc for those options.
#
#  When running this playbook, review the comments on how ths sample will
#  interact with your target, ensure you have the required authority and
#  permissions such as writing the the target directories or creating data sets.
#
#  Data sets created for this sample will follow this pattern
#  <USER>.SOME.DATA.SET where USER will be the user who submits the playbook.
#  The user is identified by the Ansible variable `ansible_user`.
#
#  Additional facts for this playbook can be configured to override the defaults
#  by reviewing the "Fact setting" section of this playbook, for example,
#  `data_set_name` and `system_name`.
#
# Requirements:
#   IBM z/OS core collection 1.1.0-beta1 or later
#   ZOAU 1.0.1 or later
#
# Configure:
#   tgt_tmp_dir - this is the USS directory on the target which will be written
#                 to for this example.
#   ctl_tmp_dir - this is the directory on the controller which will be written
#                 to for this example.
# Optional:
#   data_set_name - this is the data set name that will be created during
#                   execution of this sample.
#   system_name - this is the system name that will be used during this example,
#                 determined by executing `uname -n` on the target.
#   job_name - this is the job name what will be used in this sample, if you
#              change the HELLO.JCL job name, you must update this variable
###############################################################################

---
- hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  vars:
    tgt_tmp_dir: "/tmp"
    ctl_tmp_dir: "/tmp"
    job_name: "HELLO"
  environment: "{{ environment_vars }}"
  connection: ibm.ibm_zos_core.zos_ssh

  tasks:
    # ##########################################################################
    # Fact setting for use by this playbook
    # ##########################################################################
    - name: Setting fact `data_set_name` for use by this sample
      set_fact:
        data_set_name: "{{ ansible_user | upper }}.SOME.DATA.SET"

    - name: Fact `data_set_name` set with value
      debug:
        msg: "{{ data_set_name }}"

    - name: Detecting system name
      #shell: "uname -a |awk '{print $2}'"
      command: uname -n
      register: result

    - name: Setting fact `system_name` for use by this sample
      set_fact:
        system_name: "{{ result.stdout }}"

    - name: Fact `system_name` set with value
      debug:
        msg: "{{ system_name }}"

    ############################################################################
    # Modules zos_data_set, zos_tso_command, zos_job_submit, zos_job_query,
    # zos_job_output
    ############################################################################
    # +-------------------------------------------------------------------------
    # | Create a data set, create JCL on USS target, copy USS JCL to data set,
    # | rename data set using TSO commands, submit JCL in data set, query job,
    # | get job output, delete data set using TSO command
    # +-------------------------------------------------------------------------
    - name: Create a PDS data set {{ data_set_name }}
      zos_data_set:
        name: "{{ data_set_name }}"
        type: pds
        size: 5M
        format: fb
        record_length: 80
        replace: yes
      register: result

    - name: Response for create a PDS data set {{ data_set_name }}
      debug:
        msg: "{{ result }}"

    - name: Create a PDS member and replace if member exist
      zos_data_set:
        name: "{{ data_set_name }}(MEM{{ item }})"
        type: MEMBER
        replace: yes
      with_sequence: count=1
      register: result

    - name: Response for create a PDS member and replace if member exist
      debug:
        msg: "{{ result }}"

    - name: Ensure JCL folder exists in USS to manage JCL
      file:
        path: "{{ tgt_tmp_dir }}/ansible/jcl"
        state: directory

    - name: Write HELLO JCL to USS in {{ tgt_tmp_dir }}/ansible/jcl/HELLO"
        on target {{ inventory_hostname }}
      shell: "echo {{ lookup('file', playbook_dir + '/files/HELLO.jcl') | quote }} > {{ tgt_tmp_dir }}/ansible/jcl/HELLO"
      changed_when: true
      register: result

    - name: Response for write HELLO JCL to USS
        in {{ tgt_tmp_dir }}/ansible/jcl/HELLO" on
        target {{ inventory_hostname }}
      debug:
        msg: "{{ result }}"

    - name: Populate {{ data_set_name }} member with data from USS file in
        in {{ tgt_tmp_dir }}/ansible/jcl
      command: 'cp {{ tgt_tmp_dir }}/ansible/jcl/HELLO "//''{{ data_set_name }}(MEM{{ item }})''"'
      with_sequence: count=1
      register: result

    - name: Response for populate {{ data_set_name }} member with data from
        USS file in {{ tgt_tmp_dir }}/ansible/jcl
      debug:
        msg: "{{ result }}"

    - name: TSO commands to manage data set (LU, LISTDS, RENAME, LISTDS)
      zos_tso_command:
        commands:
          - LU {{ ansible_user }}
          - LISTDS '{{ data_set_name }}'
          - RENAME '{{ data_set_name }}' '{{ data_set_name }}.LLQ'
          - LISTDS '{{ data_set_name }}.LLQ'
      register: result

    - name: Response for TSO commands to manage data
        set (LU, LISTDS, RENAME, LISTDS)
      debug:
        msg: "{{ result }}"

    - name: Submit the JCL {{ data_set_name }}.LLQ(MEM1)
      zos_job_submit:
        src: "{{ data_set_name }}.LLQ(MEM{{ item }})"
        location: DATA_SET
        wait: true
      register: response
      with_sequence: count=1

    - name: Response for submit the JCL {{ data_set_name }}.LLQ(MEM1)
      debug:
        msg: "{{ result }}"

    - name: Query submitted job 'HELLO' in data set {{ data_set_name }}.LLQ
      zos_job_query:
        job_name: HELLO
      register: result

    - name: Response for query submitted job 'HELLO' in data
        set {{ data_set_name }}.LLQ
      debug:
        msg: "{{ result }}"

    - name: Get HELLO job output
      zos_job_output:
        job_name: HELLO
      register: result

    - name: Response for get HELLO job output
      debug:
        msg: "{{ result }}"

    - name: TSO command delete data set {{ data_set_name }}.LLQ
      zos_tso_command:
        commands:
          - DELETE '{{ data_set_name }}.LLQ'
      register: result

    - name: Response for TSO command delete data set {{ data_set_name }}.LLQ
      debug:
        msg: "{{ result }}"

    - name: Remove files on target in {{ tgt_tmp_dir }}/ansible
      file:
        path: "{{ tgt_tmp_dir }}/ansible"
        state: absent
      register: result

    - name: Response for remove files on target in {{ tgt_tmp_dir }}/ansible
      debug:
        msg: "{{ result }}"


    # +-------------------------------------------------------------------------
    # | Create a directory in USS on the target, write sample JCL on target,
    # | submit the target JCL, query for the submitted job and obtain the
    # | job output, demonstrate creating and deleting data sets
    # +-------------------------------------------------------------------------

    - name: Create directory {{ tgt_tmp_dir }}/ansible/jcl on USS
            target {{ system_name }}
      file:
        path: "{{ tgt_tmp_dir }}/ansible/jcl"
        state: directory

    - name: Write sample {{ job_name }} JCL in {{ tgt_tmp_dir }}/ansible/jcl
            on USS
            target {{ system_name }}
      shell: "echo {{ lookup('file', playbook_dir + '/files/{{job_name}}.jcl') | quote }} > {{ tgt_tmp_dir }}/ansible/jcl/{{job_name}}"
      changed_when: true
      register: result

    - name: Response for write sample {{job_name}} JCL in {{ tgt_tmp_dir }}/ansible/jcl
            on USS target {{ system_name }}
      debug:
        msg: "{{ result }}"

    - name: Submit {{job_name}} jcl located on target
            in {{ tgt_tmp_dir }}/ansible/jcl/{{job_name}}
      zos_job_submit:
        src: "{{ tgt_tmp_dir }}/ansible/jcl/{{job_name}}"
        location: USS
        wait: True

    - name: Response for submit {{job_name}} jcl located on target
            in {{ tgt_tmp_dir }}/ansible/jcl/{{job_name}}
      debug:
        msg: "{{ result }}"

    - name: Query the submitted job {{job_name}} on USS target {{ system_name }}
      zos_job_query:
        job_name: "{{job_name}}"
      register: result

    - name: Response for Query the submitted job {{job_name}}
            on USS target {{ system_name }}
      debug:
        msg: "{{ result }}"

    - name: Get {{job_name}} job output on USS target {{ system_name }}
      zos_job_output:
        job_name: "{{job_name}}"
      register: result

    - name: Response for Get {{job_name}} job output on USS target {{ system_name }}
      debug:
        msg: "{{ result }}"

    - name: Remove {{job_name}} JCL and folder on USS target {{ system_name }}
      file:
        path: "{{ tgt_tmp_dir }}/ansible"
        state: absent

    - name: Response for remove {{job_name}} JCL and folder on
            USS target {{ system_name }}
      debug:
        msg: "{{ result }}"

    - name: Create a PDS data set {{ data_set_name }}
      zos_data_set:
        name: "{{ data_set_name }}"
        type: pds
        size: 5M
        format: fb
        record_length: 25
        replace: yes
      register: result

    - name: Response create a PDS data set {{ data_set_name }}
      debug:
        msg: "{{ result }}"

    - name: Check if data set {{ data_set_name }} was created
      command: "dls {{ data_set_name }}"
      register: result
      changed_when: true

    - name: Response for check if data set {{ data_set_name }} was created
      debug:
        msg: "{{ result }}"

    - name: Delete data set {{ data_set_name }}
      zos_data_set:
        name: "{{ data_set_name }}"
        state: absent
      register: result

    - name: Response for delete data set {{ data_set_name }}
      debug:
        msg: "{{ result }}"
