################################################################################
# Copyright (c) IBM Corporation 2021
################################################################################

################################################################################
# Variables used and needing confirugation for this playbook
################################################################################

# A list of data sets contained in an archive you wish to include in dump
data_sets_to_dump:

# The name to use for the data set archive,
# if not provided, module-generated name will be used
archive_data_set: ""

# The name to use for the tersed archive data set,
# if not provided, module-generated name will be used
terse_data_set: ""

# The name to give to the tersed archive after FTP transfer,
# if not provided terse_data_set value will be used
target_data_set: ""

# The volume containing the data sets to archive,
# if input volume not provided system defaults will be used
input_volume: ""

# The host name of the target host which will receive the tersed data set
target_hostname: ""

# The user name to use for connecting to the target host
target_user: ""

# The password to use for connecting to the target host,
# can also use Ansible Vault credential
target_password: ""

# Indicates if terse and archive data sets should be deleted upon successful transfer?
delete: yes

# The python installation home path on the z/OS managed node (target),
# e.g, pyz: "/usr/lpp/IBM/cyp/v3r8/pyz"
PYZ: "path_to_python_installation_on_zos_target"

# The ZOAU installation home on the z/OS managed node (target),
# e.g, zoau: "/usr/lpp/IBM/zoautil"
ZOAU: "path_to_zoau_installation_on_zos_target"

# The z/OS managed node (target) Python binary installation path,
# e.g, ansible_python_interpreter: "{{PYZ}}/bin/python3.8"
# NOTE: This needs not configuration because it uses variable substituion to
# correctly set the variable`ansible_python_interpreter`
ansible_python_interpreter: "{{ PYZ }}/bin/python3.8"
