---
# Sample playbook for the zhmc_storage_group_attachment module of the ibm.ibm_zhmc collection:
#
# Detach a storage group from a partition
#
# Command to run this playbook:
# ansible-playbook -i inventory.yml -e hmc={myhmc} -e cpc={mycpc} -e partition={mypartition} -e stogroup={mystogroup} module_storagegroup_detach.yml

- hosts:
    - "{{ hmc | default('default') }}"  # HMC nickname from inventory entry
  gather_facts: no
  vars_files:
    - vault.yml
  vars:
    cpc: MYCPC                          # Adjust or override with -e option
    partition: sample-part-1            # Adjust or override with -e option
    stogroup: sample-sg-1               # Adjust or override with -e option
    log_file: zhmc.log
  collections:
    - ibm.ibm_zhmc
  tasks:

    - name: "Ensure storage group {{ stogroup }} is detached from partition {{ partition }}"
      delegate_to: localhost
      zhmc_storage_group_attachment:
        hmc_host: "{{ ansible_host }}"
        hmc_auth: "{{ hmc_auth[inventory_hostname] }}"
        cpc_name: "{{ cpc }}"
        storage_group_name: "{{ stogroup }}"
        partition_name: "{{ partition }}"
        state: detached
        log_file: "{{ log_file | default(omit) }}"
      register: result

    - name: Print the result
      ansible.builtin.debug:
        var: result
