---
# Sample module-level playbook of the IBM Z HMC Collection

- hosts:
    - my_hmc_list
  vars_files:
    - vault.yml
  vars:
    partition_name: sample-part-1
  collections:
    - ibm.ibm_zhmc
  tasks:

    - name: "Get facts for partition {{ partition_name }}"
      delegate_to: localhost
      zhmc_partition:
        hmc_host: "{{ ansible_host }}"
        hmc_auth: "{{ hmc_auth[inventory_hostname] }}"
        cpc_name: "{{ cpc_name }}"
        name: "{{ partition_name }}"
        state: facts
      register: result

    - name: Print the result
      debug:
        var: result
