---
# Sample module-level playbook of the IBM Z HMC Collection

- hosts:
    - my_hmc_list
  vars_files:
    - vault.yml
  vars:
    stogroup_name: sample-sg-1
  collections:
    - ibm.ibm_zhmc
  tasks:

    - name: "Ensure FCP storage group {{ stogroup_name }} exists"
      delegate_to: localhost
      zhmc_storage_group:
        hmc_host: "{{ ansible_host }}"
        hmc_auth: "{{ hmc_auth[inventory_hostname] }}"
        cpc_name: "{{ cpc_name }}"
        name: "{{ stogroup_name }}"
        properties:
          description: "This is storage group {{ stogroup_name }}"
          type: fcp
          shared: false
          connectivity: 4
          max-partitions: 1
        state: present
        expand: true
      register: result

    - name: Print the result
      debug:
        var: result
