---
# Sample module-level playbook of the IBM Z HMC Collection

- hosts:
    - my_hmc_list
  vars_files:
    - vault.yml
  vars:
    partition_name: sample-part-1
    stogroup_name: sample-sg-1
  collections:
    - ibm.ibm_zhmc
  tasks:

    - name: "Ensure storage group {{ stogroup_name }} is detached from partition {{ partition_name }}"
      delegate_to: localhost
      zhmc_storage_group_attachment:
        hmc_host: "{{ ansible_host }}"
        hmc_auth: "{{ hmc_auth[inventory_hostname] }}"
        cpc_name: "{{ cpc_name }}"
        storage_group_name: "{{ stogroup_name }}"
        partition_name: "{{ partition_name }}"
        state: detached
      register: result

    - name: Print the result
      debug:
        var: result
