---
# Sample module-level playbook of the IBM Z HMC Collection

- hosts:
    - my_hmc_list
  vars_files:
    - vault.yml
  vars:
    hs_adapter_name: sample-hs-1
  collections:
    - ibm.ibm_zhmc
  tasks:

    - name: "Ensure a Hipersockets adapter {{ hs_adapter_name }} exists and has the desired property values"
      delegate_to: localhost
      ibm.ibm_zhmc.zhmc_adapter:
        hmc_host: "{{ ansible_host }}"
        hmc_auth: "{{ hmc_auth[inventory_hostname] }}"
        cpc_name: "{{ cpc_name }}"
        name: "{{ hs_adapter_name }}"
        state: present
        properties:
          type: hipersockets
          description: "This is Hipersockets adapter {{ hs_adapter_name }}"
      register: result

    - name: Print the result
      ansible.builtin.debug:
        var: result
