---
# Sample module-level playbook of the IBM Z HMC Collection

- hosts:
    - my_hmc_list
  vars_files:
    - vault.yml
  collections:
    - ibm.ibm_zhmc
  tasks:

    - name: "Get facts for CPC {{ cpc_name }}"
      delegate_to: localhost
      zhmc_cpc:
        hmc_host: "{{ ansible_host }}"
        hmc_auth: "{{ hmc_auth[inventory_hostname] }}"
        name: "{{ cpc_name }}"
        state: facts
      register: result

    - name: Print the result
      debug:
        var: result
