---
# Sample playbook for the zhmc_storage_volume module of the ibm.ibm_zhmc collection:
#
# Get facts about a storage volume
#
# Command to run this playbook:
# ansible-playbook -i inventory.yml -e hmc={myhmc} -e cpc={mycpc} -e stogroup={mystogroup} -e stovolume={mystovolume} module_storagevolume_facts.yml

- hosts:
    - "{{ hmc | default('default') }}"  # HMC nickname from inventory entry
  gather_facts: no
  vars_files:
    - vault.yml
  vars:
    cpc: MYCPC                          # Adjust or override with -e option
    stogroup: sample-sg-1               # Adjust or override with -e option
    stovolume: sample-sv-1              # Adjust or override with -e option
    log_file: zhmc.log
  collections:
    - ibm.ibm_zhmc
  tasks:

    - name: "Get facts for storage volume {{ stovolume }} of storage group {{ stogroup }}"
      delegate_to: localhost
      zhmc_storage_volume:
        hmc_host: "{{ ansible_host }}"
        hmc_auth: "{{ hmc_auth[inventory_hostname] }}"
        cpc_name: "{{ cpc }}"
        storage_group_name: "{{ stogroup }}"
        name: "{{ stovolume }}"
        state: facts
        log_file: "{{ log_file | default(omit) }}"
      register: result

    - name: Print the result
      ansible.builtin.debug:
        var: result
