---
# Sample playbook for the zhmc_crypto_attachment module of the ibm.ibm_zhmc collection:
#
# Get facts about the crypto config of a partition
#
# Command to run this playbook:
# ansible-playbook -i inventory.yml -e hmc={myhmc} -e cpc={mycpc} -e partition={mypartition} module_crypto_attachment_facts.yml

- hosts:
    - "{{ hmc | default('default') }}"  # HMC nickname from inventory entry
  gather_facts: no
  vars_files:
    - vault.yml
  vars:
    cpc: MYCPC                          # Adjust or override with -e option
    partition: sample-part-1            # Adjust or override with -e option
    log_file: zhmc.log
  collections:
    - ibm.ibm_zhmc
  tasks:

    - name: "Get facts for crypto config of partition {{ partition }}"
      delegate_to: localhost
      zhmc_crypto_attachment:
        hmc_host: "{{ ansible_host }}"
        hmc_auth: "{{ hmc_auth[inventory_hostname] }}"
        cpc_name: "{{ cpc }}"
        partition_name: "{{ partition }}"
        state: facts
        log_file: "{{ log_file | default(omit) }}"
      register: result

    - name: Print the result
      ansible.builtin.debug:
        var: result
