---
# Sample module-level playbook of the IBM Z HMC Collection

- hosts:
    - my_hmc_list
  vars_files:
    - vault.yml
  vars:
    hs_adapter_name: sample-hs-1
  collections:
    - ibm.ibm_zhmc
  tasks:
    - name: "Ensure Hipersockets adapter {{ hs_adapter_name }} does not exist"
      delegate_to: localhost
      zhmc_adapter:
        hmc_host: "{{ ansible_host }}"
        hmc_auth: "{{ hmc_auth[inventory_hostname] }}"
        cpc_name: "{{ cpc_name }}"
        name: "{{ hs_adapter_name }}"
        state: absent
      register: result

    - name: Print the result
      debug:
        var: result
