---
# Sample module-level playbook of the IBM Z HMC Collection

- hosts:
    - my_hmc_list
  vars_files:
    - vault.yml
  vars:
    partition_name: sample-part-1
  collections:
    - ibm.ibm_zhmc
  tasks:

    - name: "Ensure domains 2..max on 2 arbitrary adapters are attached to partition {{ partition_name }}"
      delegate_to: localhost
      zhmc_crypto_attachment:
        hmc_host: "{{ hmc_host }}"
        hmc_auth: "{{ hmc_auth }}"
        cpc_name: "{{ cpc_name }}"
        partition_name: "{{ partition_name }}"
        state: attached
        crypto_type: ep11
        adapter_count: 2
        domain_range: 2,-1
        access_mode: usage
      register: result

    - name: Print the resultâ€š
      debug:
        var: result
