name: ansible-lint
on: [push, pull_request] # noqa: yaml[truthy]

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install dependencies from Ansible Galaxy
        uses: ./.github/actions/install-requirements
        with:
          requirements: collections/requirements.yml

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25.8.2
