# =================================================================
# Licensed Materials - Property of IBM
#
# (c) Copyright IBM Corp. 2021 All Rights Reserved
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
# =================================================================

---
# tasks file for configure-installer-and-image

- name: Download openshift installer
  become: yes
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/{{ ansible_architecture }}/clients/ocp/{{ openshift_version }}.{{ openshift_minor_version }}/openshift-install-linux.tar.gz
    dest: .
    mode: 0755

- name: Unzip openshift installer
  command:
    cmd: tar -zvxf openshift-install-linux.tar.gz
  
- name: Remove openshift installer archive
  file:
    state: absent
    path: openshift-install-linux.tar.gz

- name: Download openshift client
  become: yes
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/{{ ansible_architecture }}/clients/ocp/{{ openshift_version }}.{{ openshift_minor_version }}/openshift-client-linux.tar.gz
    dest: .
    mode: 0755

- name: Unzip openshift client archive
  command:
    cmd: tar -zvxf openshift-client-linux.tar.gz
  
- name: Remove openshift client archive
  file:
    state: absent
    path: openshift-client-linux.tar.gz

- name: Remove openshift RHCOS images
  file:
    state: absent
    path: rhcos-{{ openshift_version }}.{{ openshift_minor_version }}-s390x.raw.gz
    
- name: Download RHCOS image
  become: yes
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/{{ ansible_architecture }}/dependencies/rhcos/{{ openshift_version }}/{{ openshift_version }}.{{ openshift_minor_version }}/rhcos-{{ openshift_version }}.{{ openshift_minor_version }}-s390x-metal.s390x.raw.gz
    dest: ./rhcos-{{ openshift_version }}.{{ openshift_minor_version }}-s390x.raw.gz
    mode: 0755
  when: 
  - vm_type == "zvm"
  - disk_type == "scsi"

- name: Download RHCOS image
  become: yes
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/{{ ansible_architecture }}/dependencies/rhcos/{{ openshift_version }}/{{ openshift_version }}.{{ openshift_minor_version }}/rhcos-{{ openshift_version }}.{{ openshift_minor_version }}-s390x-dasd.s390x.raw.gz
    dest: ./rhcos-{{ openshift_version }}.{{ openshift_minor_version }}-s390x.raw.gz
    mode: 0755
  when: 
  - vm_type == "zvm"
  - disk_type == "dasd"

- name: Unzip RHCOS image
  command:
    cmd: gzip -d -f rhcos-{{ openshift_version }}.{{ openshift_minor_version }}-s390x.raw.gz
  when: 
  - vm_type == "zvm"

- name: Upload RHCOS image to ICIC glance
  command: 
    cmd: openstack image create --disk-format=raw  --property architecture=s390x --property os_name=Linux --property os_version=RHCOS{{ openshift_version }} --property os_distro=RHCOS{{ openshift_version }} --property hypervisor_type=ZVM --property disk_type=SCSI --file=rhcos-{{ openshift_version }}.{{ openshift_minor_version }}-s390x.raw rhcos
  when: 
  - vm_type == "zvm"
  - disk_type == "scsi"

- name: Upload RHCOS image to ICIC glance
  command: 
    cmd: openstack image create --disk-format=raw  --property architecture=s390x --property os_name=Linux --property os_version=RHCOS{{ openshift_version }} --property os_distro=RHCOS{{ openshift_version }} --property hypervisor_type=ZVM --property disk_type=DASD --file=rhcos-{{ openshift_version }}.{{ openshift_minor_version }}-s390x.raw rhcos
  when: 
  - vm_type == "zvm"
  - disk_type == "dasd"

- name: Remove openshift RHCOS images
  file:
    state: absent
    path: rhcos-{{ openshift_version }}.{{ openshift_minor_version }}-s390x.qcow2.gz

- name: Download RHCOS image
  become: yes
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/{{ ansible_architecture }}/dependencies/rhcos/{{ openshift_version }}/{{ openshift_version }}.{{ openshift_minor_version }}/rhcos-{{ openshift_version }}.{{ openshift_minor_version }}-s390x-openstack.s390x.qcow2.gz
    dest: ./rhcos-{{ openshift_version }}.{{ openshift_minor_version }}-s390x.qcow2.gz
    mode: 0755
  when: 
  - vm_type == "kvm"

- name: Unzip RHCOS image
  command:
    cmd: gzip -d rhcos-{{ openshift_version }}.{{ openshift_minor_version }}-s390x.qcow2.gz
  when: 
  - vm_type == "kvm"

- name: Upload RHCOS image to ICIC glance
  command: 
    cmd: openstack image create --disk-format=qcow2 --property architecture=s390x --property os_name=Linux --property os_version=RHCOS{{ openshift_version }} --property os_distro=RHCOS{{ openshift_version }} --property hypervisor_type=kvm --file=rhcos-{{ openshift_version }}.{{ openshift_minor_version }}-s390x.qcow2 rhcos
  when: 
  - vm_type == "kvm"

- name: Remove local RHCOS image
  file:
    state: absent
    path: rhcos-{{ openshift_version }}.{{ openshift_minor_version }}-s390x.raw
  when: 
  - vm_type == "zvm"

- name: Remove local RHCOS image
  file:
    state: absent
    path: rhcos-{{ openshift_version }}.{{ openshift_minor_version }}-s390x.qcow2
  when: 
  - vm_type == "kvm"
